version: "3.7"

networks:
  laravel:

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80 # To change host access port number
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/var/www/html # To change project folder name
    depends_on:
      - php-fpm
    networks:
      - laravel

  php-fpm:
    build:
      context: ./php-fpm
      target: dev
    working_dir: /var/www/html
    volumes:
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./laravel:/var/www/html # To change project folder name
    depends_on:
      - mysql
      - phpmyadmin
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-db
    ports:
      - 3306:3306 # To change mysql port number
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app # To change database name
    volumes:
      - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - laravel

  phpmyadmin: # This is for mysql GUI view in windows
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    networks:
      - laravel

volumes:
  db-data:
